version: ~> 1.0

os: linux
language: java

jdk:
  - openjdk11

script:
  - ./gradlew installDist
  - ./build/install/eclipse-board-game/bin/eclipse-board-game

branches:
  only:
    - master

deploy:
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: public
  target_branch: gh-pages
